name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: emacs-eldev/setup-eldev@v1
    - name: Install dependencies
      run: |
        eldev prepare
    - name: Run tests
      run: |
        eldev -p -dtT test